import { Canvas, loadSVGFromURL, loadSVGFromString } from "fabric";
import { useEffect } from "react";

const object = {
  resId: "asset_svg_44",
  isSvg: true,
  id: "PJxJJRHg24",
  type: "Polygon",
  objectCaching: false,
  selectable: true,
  transparentCorners: false,
  hasBorders: true,
  hasControls: true,
  padding: 0,
  lockMovementX: false,
  lockMovementY: false,
  version: "6.7.0",
  originX: "left",
  originY: "top",
  left: 0,
  top: 0,
  width: 576,
  height: 1052,
  fill: "#7230A5",
  stroke: null,
  strokeWidth: 1,
  strokeDashArray: null,
  strokeLineCap: "butt",
  strokeDashOffset: 0,
  strokeLineJoin: "miter",
  strokeUniform: false,
  strokeMiterLimit: 4,
  scaleX: 1,
  scaleY: 1,
  angle: 0,
  flipX: false,
  flipY: false,
  opacity: 1,
  shadow: null,
  visible: true,
  backgroundColor: "",
  fillRule: "nonzero",
  paintFirst: "stroke",
  globalCompositeOperation: "source-over",
  skewX: 0,
  skewY: 0,
  points: [
    {
      x: 612.9,
      y: 962.9,
    },
    {
      x: 596.1,
      y: 994.1,
    },
    {
      x: 84.2,
      y: 15.9,
    },
    {
      x: 117.5,
      y: 16.2,
    },
  ],
};

const data = {
  id: "APxCmQX_hz",
  name: "企业印刷名片",
  width: 500,
  height: 500,
  zoom: 1,
  left: 0,
  top: 0,
  version: "6.6",
  objects: [
    {
      rx: 0,
      ry: 0,
      id: "WorkSpaceDrawType",
      name: "rect",
      color: "#ffffff",
      padding: 0,
      fill: "#eee",
      selectable: false,
      evented: false,
      fillType: 0,
      lockMovementX: false,
      lockMovementY: false,
      objectCaching: true,
      transparentCorners: false,
      hasBorders: false,
      globalCompositeOperation: "source-over",
      absolutePositioned: false,
      type: "Rect",
      version: "6.7.1",
      originX: "left",
      originY: "top",
      left: 0,
      top: 0,
      width: 1063.2273,
      height: 637.9364,
      stroke: "",
      strokeWidth: 0,
      strokeDashArray: null,
      strokeLineCap: "butt",
      strokeDashOffset: 0,
      strokeLineJoin: "miter",
      strokeUniform: false,
      strokeMiterLimit: 0,
      scaleX: 1,
      scaleY: 1,
      angle: 0,
      flipX: false,
      flipY: false,
      opacity: 1,
      shadow: null,
      visible: true,
      backgroundColor: "rgba(0,0,0,0)",
      fillRule: "nonzero",
      paintFirst: "fill",
      skewX: 0,
      skewY: 0,
    },
    {
      cropX: 200,
      cropY: 200,
      id: "arw5PYpXuY",
      name: "image",
      padding: 0,
      cropKey: "arrow",
      cropPath:
        "M -172.27223986771315 -62.68213179990151 L 34.454447973542635 -62.68213179990151 L 34.454447973542635 -104.47021966650253 L 172.27223986771315 0 L 34.454447973542635 104.47021966650253 L 34.454447973542635 62.68213179990151 L -172.27223986771315 62.68213179990151 Z",
      fill: "rgb(0,0,0)",
      selectable: true,
      evented: true,
      lockMovementX: false,
      lockMovementY: false,
      objectCaching: true,
      transparentCorners: false,
      hasBorders: true,

      globalCompositeOperation: "source-over",
      absolutePositioned: false,
      clipPath: {
        padding: 0,
        fill: "rgb(0,0,0)",
        selectable: true,
        evented: true,
        lockMovementX: false,
        lockMovementY: false,
        objectCaching: true,
        transparentCorners: false,
        hasBorders: true,
        effects: {
          stroke: [],
          solidFill: [],
          outerGlow: {},
          gradientOverlay: [],
          innerShadow: [],
          innerGlow: {},
          bevel: {},
          satin: {},
        },
        globalCompositeOperation: "source-over",
        absolutePositioned: false,
        pathOffset: {
          x: 0,
          y: 0,
        },
        inverted: false,
        type: "Path",
        version: "6.7.1",
        originX: "left",
        originY: "top",
        left: -172.7722,
        top: -104.9702,
        width: 344.5445,
        height: 208.9404,
        // width: 100,
        // height: 50,
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: true,
        strokeMiterLimit: 4,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        skewX: 0,
        skewY: 0,
        path: [
          ["M", -172.27223986771315, -62.68213179990151],
          ["L", 34.454447973542635, -62.68213179990151],
          ["L", 34.454447973542635, -104.47021966650253],
          ["L", 172.27223986771315, 0],
          ["L", 34.454447973542635, 104.47021966650253],
          ["L", 34.454447973542635, 62.68213179990151],
          ["L", -172.27223986771315, 62.68213179990151],
          ["Z"],
        ],
      },
      type: "Image",
      version: "6.7.1",
      originX: "left",
      originY: "top",
      left: 100,
      top: 100,
      width: 200,
      height: 100,
      stroke: null,
      strokeWidth: 0,
      strokeDashArray: null,
      strokeLineCap: "butt",
      strokeDashOffset: 0,
      strokeLineJoin: "miter",
      strokeUniform: false,
      strokeMiterLimit: 4,
      scaleX: 0.5,
      scaleY: 0.5,
      angle: 0,
      flipX: false,
      flipY: false,
      opacity: 1,
      shadow: null,
      visible: true,
      backgroundColor: "",
      fillRule: "nonzero",
      paintFirst: "fill",
      skewX: 0,
      skewY: 0,
      src: "https://images.pexels.com/photos/290275/pexels-photo-290275.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
      crossOrigin: "anonymous",
      filters: [],
      imageWidth: 650,
      imageHeight: 650,
    },
  ],
  workSpace: {
    fillType: 0,
    left: 0,
    top: 0,
    angle: 0,
    scaleX: 1,
    scaleY: 1,
    color: "#ffffff",
    fill: "#ffffff",
    backgroundColor: "rgba(0,0,0,0)",
  },
};

// const svg = "https://js.pngtree.com/editor/assets/mask_v_561.svg";
const svg = "https://js.pngtree.com/editor/assets/mask_v_220.svg";
const svg1 = "https://js.pngtree.com/editor/assets/svg_v_22.svg";

export default () => {
  useEffect(() => {
    const canvasDom = document.getElementById("canvas") as HTMLCanvasElement;
    console.log(canvasDom);

    const canvas = new Canvas(canvasDom);
    // canvas.loadFromJSON({ objects: [object, { type: "IText", text: "1234" }] });
    canvas.loadFromJSON(data);
    canvas.requestRenderAll();

    loadSVGFromURL(svg).then((res) => {
      console.log(res);
    });
    loadSVGFromURL(svg1).then((res) => {
      console.log(res);
    });

    loadSVGFromString(
      `<svg> <rect id="SVGID_1_" x="0.5" y="0.5" width="599" height="600"/> </svg>`
    ).then((res) => {
      console.log("loadSVGFromString", res);
      res.objects.forEach((item) => {
        console.log(item?.width, item?.height);
      });
    });
  }, []);
  return <canvas id="canvas" width={data.width} height={data.height} />;
};
