export interface TemplateListItem {
  audit_through: string;
  author: string;
  avatar_group_word_id: null | string | number;
  brief: string;
  created: string;
  deleted: string;
  description: string;
  dpi: string;
  edit: string;
  height: string;
  hide_description: null | string;
  hide_in_ios: string;
  host: string;
  id: string;
  imgUrl: string;
  is_zb: 'string';
  kid_1: string;
  kid_2: string;
  kid_3: string;
  online_time: null | string;
  pages: string;
  duration: number;
  pr: string;
  preview: string;
  protocol: string;
  position: number;
  ratio: string;
  res_id: string;
  set_id: string;
  small: string;
  small_url: string;
  templ_info: string;
  template_type: string;
  title: string;
  tmp: string;
  txt_debug: string;
  updated: string;
  use_shetu: string;
  use_zihun: string;
  width: string;
  isFav: boolean;
}
