export default [
  {
    name: "Base",
    items: [
      {
        id: "1",
        name: "Bright Warm Color",
        preview_url: "https://js.pngtree.com/filter/img/img_filter/1.jpg",
        filters: {
          blur: 0,
          brightness: 0.025,
          contrast: 0.125,
          "gamma-b": 1,
          "gamma-g": 1.3,
          "gamma-r": 2.2,
          hue: 0,
          saturate: 0.38,
          sharpen: 0,
          strong: 0.8,
        },
      },
      {
        id: "2",
        name: "Bright Cool Color",
        preview_url: "https://js.pngtree.com/filter/img/img_filter/2.jpg",
        filters: {
          blur: 0,
          brightness: -0.0375,
          contrast: 0.125,
          "gamma-b": 1,
          "gamma-g": 0.775,
          "gamma-r": 0.7,
          hue: 0,
          saturate: 0.25,
          sharpen: 0,
          strong: 0.8,
        },
      },
      {
        id: "3",
        name: "Contrasting Warm Colors",
        preview_url: "https://js.pngtree.com/filter/img/img_filter/3.jpg",
        filters: {
          blur: 0,
          brightness: -0.025,
          contrast: -0.125,
          "gamma-b": 1,
          "gamma-g": 1.2,
          "gamma-r": 1.75,
          hue: 0,
          saturate: -0.5,
          sharpen: 0,
          strong: 0.8,
        },
      },
      {
        id: "4",
        name: "Cool Contrast",
        preview_url: "https://js.pngtree.com/filter/img/img_filter/4.jpg",
        filters: {
          blur: 0,
          brightness: 0.0375,
          contrast: -0.125,
          "gamma-b": 1,
          "gamma-g": 0.775,
          "gamma-r": 0.4,
          hue: 0,
          saturate: -0.375,
          sharpen: 0,
          strong: 0.8,
        },
      },
      {
        id: "5",
        name: "Monochrome",
        preview_url: "https://js.pngtree.com/filter/img/img_filter/5.jpg",
        filters: {
          blur: 0,
          brightness: 0,
          contrast: 0,
          "gamma-b": 1,
          "gamma-g": 1,
          "gamma-r": 1,
          hue: 0,
          saturate: -1,
          sharpen: 0,
          strong: 1,
        },
      },
      {
        id: "6",
        name: "Vague",
        preview_url: "https://js.pngtree.com/filter/img/img_filter/6.jpg",
        filters: {
          blur: 0.4,
          brightness: 0,
          contrast: 0,
          "gamma-b": 1,
          "gamma-g": 1,
          "gamma-r": 1,
          hue: 0,
          saturate: 0,
          sharpen: 0,
          strong: 1,
        },
      },
      {
        id: "7",
        name: "Hong Kong Style",
        preview_url: "https://js.pngtree.com/filter/img/img_filter/7.jpg",
        filters: {
          blur: 0,
          brightness: -0.01,
          contrast: 0.04,
          "gamma-b": 0.75,
          "gamma-g": 1.04,
          "gamma-r": 1.75,
          hue: 0.06,
          saturate: 0.13,
          sharpen: 0,
          strong: 0.8,
        },
      },
      {
        id: "8",
        name: "Fresh",
        preview_url: "https://js.pngtree.com/filter/img/img_filter/8.jpg",
        filters: {
          blur: 0,
          brightness: 0.01,
          contrast: 0.03,
          "gamma-b": 1.23,
          "gamma-g": 1.04,
          "gamma-r": 1.1,
          hue: 0.04,
          saturate: -0.03,
          sharpen: 0,
          strong: 0.8,
        },
      },
      {
        id: "9",
        name: "And Wind",
        preview_url: "https://js.pngtree.com/filter/img/img_filter/9.jpg",
        filters: {
          blur: 0,
          brightness: 0.06,
          contrast: 0,
          "gamma-b": 0.81,
          "gamma-g": 1.11,
          "gamma-r": 0.76,
          hue: -0.03,
          saturate: -0.25,
          sharpen: 0,
          strong: 0.8,
        },
      },
      {
        id: "10",
        name: "Fresh",
        preview_url: "https://js.pngtree.com/filter/img/img_filter/10.jpg",
        filters: {
          blur: 0,
          brightness: 0.04,
          contrast: 0.03,
          "gamma-b": 1.23,
          "gamma-g": 1.35,
          "gamma-r": 0.9,
          hue: -0.05,
          saturate: -0.1,
          sharpen: 0,
          strong: 0.8,
        },
      },
      {
        id: "11",
        name: "Film",
        preview_url: "https://js.pngtree.com/filter/img/img_filter/11.jpg",
        filters: {
          blur: 0,
          brightness: 0.04,
          contrast: -0.01,
          "gamma-b": 0.81,
          "gamma-g": 0.97,
          "gamma-r": 1.33,
          hue: -0.03,
          saturate: -0.28,
          sharpen: 0,
          strong: 0.8,
        },
      },
    ],
  },
  {
    name: "figure",
    items: [
      {
        id: "12",
        name: "Soft",
        preview_url: "https://js.pngtree.com/filter/img/img_filter/17.jpg",
        filters: {
          blur: 0,
          brightness: -0.008,
          contrast: 0.03,
          "gamma-b": 0.673,
          "gamma-g": 1.064,
          "gamma-r": 1.348,
          hue: 0,
          saturate: 0.08,
          sharpen: 0,
          strong: 0.8,
        },
      },
      {
        id: "13",
        name: "Mori Department",
        preview_url: "https://js.pngtree.com/filter/img/img_filter/18.jpg",
        filters: {
          blur: 0,
          brightness: 0.016,
          contrast: 0.02,
          "gamma-b": 1.456,
          "gamma-g": 1.24,
          "gamma-r": 1.024,
          hue: -0.04,
          saturate: 0.1,
          sharpen: 0,
          strong: 0.8,
        },
      },
      {
        id: "14",
        name: "Cool Tone",
        preview_url: "https://js.pngtree.com/filter/img/img_filter/19.jpg",
        filters: {
          blur: 0,
          brightness: 0.024,
          contrast: 0.01,
          "gamma-b": 1.48,
          "gamma-g": 1.112,
          "gamma-r": 1.048,
          hue: 0,
          saturate: -0.04,
          sharpen: 0,
          strong: 0.8,
        },
      },
      {
        id: "15",
        name: "Film",
        preview_url: "https://js.pngtree.com/filter/img/img_filter/20.jpg",
        filters: {
          blur: 0,
          brightness: 0.024,
          contrast: -0.04,
          "gamma-b": 1.144,
          "gamma-g": 1.376,
          "gamma-r": 1.42,
          hue: 0,
          saturate: 0.08,
          sharpen: 0,
          strong: 0.8,
        },
      },
      {
        id: "16",
        name: "Fresh",
        preview_url: "https://js.pngtree.com/filter/img/img_filter/21.jpg",
        filters: {
          blur: 0,
          brightness: 0.024,
          contrast: -0.03,
          "gamma-b": 1.216,
          "gamma-g": 1.28,
          "gamma-r": 1.12,
          hue: 0,
          saturate: -0.08,
          sharpen: 0,
          strong: 0.8,
        },
      },
    ],
  },
  {
    name: "Food",
    items: [
      {
        id: "17",
        name: "Warm Food",
        preview_url: "https://js.pngtree.com/filter/img/img_filter/22.jpg",
        filters: {
          blur: 0,
          brightness: 0.008,
          contrast: 0.05,
          "gamma-b": 1.108,
          "gamma-g": 1.072,
          "gamma-r": 1.216,
          hue: 0.04,
          saturate: 0.18,
          sharpen: 0,
          strong: 0.8,
        },
      },
      {
        id: "18",
        name: "Tasty",
        preview_url: "https://js.pngtree.com/filter/img/img_filter/23.jpg",
        filters: {
          blur: 0,
          brightness: 0.008,
          contrast: 0.04,
          "gamma-b": 1.096,
          "gamma-g": 1.08,
          "gamma-r": 1.264,
          hue: 0.04,
          saturate: 0.13,
          sharpen: 0,
          strong: 0.8,
        },
      },
      {
        id: "19",
        name: "Full-bodied",
        preview_url: "https://js.pngtree.com/filter/img/img_filter/24.jpg",
        filters: {
          blur: 0,
          brightness: 0.032,
          contrast: 0.03,
          "gamma-b": 1.144,
          "gamma-g": 1.176,
          "gamma-r": 1.564,
          hue: 0.04,
          saturate: 0.56,
          sharpen: 0,
          strong: 0.8,
        },
      },
      {
        id: "20",
        name: "Light Meal",
        preview_url: "https://js.pngtree.com/filter/img/img_filter/25.jpg",
        filters: {
          blur: 0,
          brightness: 0.032,
          contrast: -0.04,
          "gamma-b": 0.97,
          "gamma-g": 1.04,
          "gamma-r": 1.036,
          hue: -0.06,
          saturate: 0.09,
          sharpen: 0,
          strong: 0.8,
        },
      },
      {
        id: "21",
        name: "Milkshake",
        preview_url: "https://js.pngtree.com/filter/img/img_filter/26.jpg",
        filters: {
          blur: 0,
          brightness: 0.008,
          contrast: -0.03,
          "gamma-b": 0.871,
          "gamma-g": 0.97,
          "gamma-r": 1.192,
          hue: 0.04,
          saturate: -0.05,
          sharpen: 0,
          strong: 0.8,
          filters: 1,
        },
      },
    ],
  },
  {
    name: "landscape",
    items: [
      {
        id: "22",
        name: "Cool",
        preview_url: "https://js.pngtree.com/filter/img/img_filter/27.jpg",
        filters: {
          blur: 0,
          brightness: 0.048,
          contrast: 0,
          "gamma-b": 0.822,
          "gamma-g": 1.048,
          "gamma-r": 1.096,
          hue: -0.02,
          saturate: -0.2,
          sharpen: 0,
          strong: 0.8,
        },
      },
      {
        id: "23",
        name: "Nature",
        preview_url: "https://js.pngtree.com/filter/img/img_filter/28.jpg",
        filters: {
          blur: 0,
          brightness: 0.032,
          contrast: -0.01,
          "gamma-b": 0.703,
          "gamma-g": 1.32,
          "gamma-r": 1.192,
          hue: -0.02,
          saturate: -0.1,
          sharpen: 0,
          strong: 0.8,
        },
      },
      {
        id: "24",
        name: "Fresh",
        preview_url: "https://js.pngtree.com/filter/img/img_filter/29.jpg",
        filters: {
          blur: 0,
          brightness: 0.032,
          contrast: -0.01,
          "gamma-b": 0.871,
          "gamma-g": 1.344,
          "gamma-r": 1.096,
          hue: -0.02,
          saturate: -0.1,
          sharpen: 0,
          strong: 0.8,
        },
      },
      {
        id: "25",
        name: "Early Morning",
        preview_url: "https://js.pngtree.com/filter/img/img_filter/30.jpg",
        filters: {
          blur: 0,
          brightness: 0.032,
          contrast: -0.01,
          "gamma-b": 1.204,
          "gamma-g": 1.264,
          "gamma-r": 1.12,
          hue: -0.02,
          saturate: -0.1,
          sharpen: 0,
          strong: 0.8,
        },
      },
      {
        id: "26",
        name: "Pink Summer",
        preview_url: "https://js.pngtree.com/filter/img/img_filter/31.jpg",
        filters: {
          blur: 0,
          brightness: 0.032,
          contrast: -0.02,
          "gamma-b": 1.144,
          "gamma-g": 1,
          "gamma-r": 1.648,
          hue: -0.04,
          saturate: 0.1,
          sharpen: 0,
          strong: 0.8,
        },
      },
    ],
  },
  {
    name: "texture",
    items: [
      {
        id: "27",
        name: "Film",
        preview_url: "https://js.pngtree.com/filter/img/img_filter/32.jpg",
        filters: {
          blur: 0,
          brightness: 0.03,
          contrast: 0.02,
          "gamma-b": 1.204,
          "gamma-g": 1.072,
          "gamma-r": 1.096,
          hue: -0.04,
          saturate: -0.08,
          sharpen: 0,
          strong: 0.8,
        },
      },
      {
        id: "28",
        name: "Movie",
        preview_url: "https://js.pngtree.com/filter/img/img_filter/33.jpg",
        filters: {
          blur: 0,
          brightness: -0.008,
          contrast: -0.03,
          "gamma-b": 1.072,
          "gamma-g": 1.344,
          "gamma-r": 1.168,
          hue: 0.02,
          saturate: 0.03,
          sharpen: 0,
          strong: 0.8,
        },
      },
      {
        id: "29",
        name: "Warm Color",
        preview_url: "https://js.pngtree.com/filter/img/img_filter/34.jpg",
        filters: {
          blur: 0,
          brightness: -0.008,
          contrast: 0.01,
          "gamma-b": 1.228,
          "gamma-g": 1.344,
          "gamma-r": 1.864,
          hue: 0.02,
          saturate: 0.1,
          sharpen: 0,
          strong: 0.8,
        },
      },
      {
        id: "30",
        name: "Still Life",
        preview_url: "https://js.pngtree.com/filter/img/img_filter/35.jpg",
        filters: {
          blur: 0,
          brightness: 0,
          contrast: 0.02,
          "gamma-b": 1.672,
          "gamma-g": 1.376,
          "gamma-r": 1.132,
          hue: 0.01,
          saturate: 0.44,
          sharpen: 0,
          strong: 0.8,
        },
      },
      {
        id: "31",
        name: "Azure",
        preview_url: "https://js.pngtree.com/filter/img/img_filter/36.jpg",
        filters: {
          blur: 0,
          brightness: 0.024,
          contrast: -0.01,
          "gamma-b": 1.36,
          "gamma-g": 1.552,
          "gamma-r": 1.228,
          hue: 0.01,
          saturate: 0.04,
          sharpen: 0,
          strong: 0.8,
        },
      },
    ],
  },
];
