// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import routeProps from './routeProps';

if (process.env.NODE_ENV === 'development') {
  Object.entries(routeProps).forEach(([key, value]) => {
    const internalProps = ['path', 'id', 'parentId', 'isLayout', 'isWrapper', 'layout', 'clientLoader'];
    Object.keys(value).forEach((prop) => {
      if (internalProps.includes(prop)) {
        throw new Error(
          `[UmiJS] route '${key}' should not have '${prop}' prop, please remove this property in 'routeProps'.`
        )
      }
    })
  })
}

import React from 'react';

export async function getRoutes() {
  const routes = {"canvas/UndoRedoManager":{"path":"canvas/UndoRedoManager","id":"canvas/UndoRedoManager","parentId":"@@/global-layout"},"photo_frame/index":{"path":"photo_frame","id":"photo_frame/index","parentId":"@@/global-layout"},"canvas/adapter":{"path":"canvas/adapter","id":"canvas/adapter","parentId":"@@/global-layout"},"canvas/typing":{"path":"canvas/typing","id":"canvas/typing","parentId":"@@/global-layout"},"zoom/controls":{"path":"zoom/controls","id":"zoom/controls","parentId":"@@/global-layout"},"canvas/index":{"path":"canvas","id":"canvas/index","parentId":"@@/global-layout"},"canvas/store":{"path":"canvas/store","id":"canvas/store","parentId":"@@/global-layout"},"canvas/utils":{"path":"canvas/utils","id":"canvas/utils","parentId":"@@/global-layout"},"zoom/example":{"path":"zoom/example","id":"zoom/example","parentId":"@@/global-layout"},"canvas/test":{"path":"canvas/test","id":"canvas/test","parentId":"@@/global-layout"},"zoom/index":{"path":"zoom","id":"zoom/index","parentId":"@@/global-layout"},"index":{"path":"/","id":"index","parentId":"@@/global-layout"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'canvas/UndoRedoManager': React.lazy(() => import(/* webpackChunkName: "src__pages__canvas__UndoRedoManager" */'../../../src/pages/canvas/UndoRedoManager.ts')),
'photo_frame/index': React.lazy(() => import(/* webpackChunkName: "src__pages__photo_frame__index" */'../../../src/pages/photo_frame/index.tsx')),
'canvas/adapter': React.lazy(() => import(/* webpackChunkName: "src__pages__canvas__adapter" */'../../../src/pages/canvas/adapter.ts')),
'canvas/typing': React.lazy(() => import(/* webpackChunkName: "src__pages__canvas__typing" */'../../../src/pages/canvas/typing.ts')),
'zoom/controls': React.lazy(() => import(/* webpackChunkName: "src__pages__zoom__controls" */'../../../src/pages/zoom/controls.tsx')),
'canvas/index': React.lazy(() => import(/* webpackChunkName: "src__pages__canvas__index" */'../../../src/pages/canvas/index.tsx')),
'canvas/store': React.lazy(() => import(/* webpackChunkName: "src__pages__canvas__store" */'../../../src/pages/canvas/store.ts')),
'canvas/utils': React.lazy(() => import(/* webpackChunkName: "src__pages__canvas__utils" */'../../../src/pages/canvas/utils.ts')),
'zoom/example': React.lazy(() => import(/* webpackChunkName: "src__pages__zoom__example" */'../../../src/pages/zoom/example.tsx')),
'canvas/test': React.lazy(() => import(/* webpackChunkName: "src__pages__canvas__test" */'../../../src/pages/canvas/test.ts')),
'zoom/index': React.lazy(() => import(/* webpackChunkName: "src__pages__zoom__index" */'../../../src/pages/zoom/index.tsx')),
'index': React.lazy(() => import(/* webpackChunkName: "src__pages__index" */'../../../src/pages/index.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'/Users/craig/Desktop/wqy/demo/wang-qyy.github.io/umi-max/src/layouts/index.tsx')),
},
  };
}
