const popular = {
  type: "popular_tools",
  title: "Popular Tools",
  img: "https://js.seapik.com/image/content-generator/20231031/icon_3.png",
  children: [
    {
      parent_type: "popular_tools",
      type: "email",
      title: "Email ai writer",
      desc: "Quickly generate engaging emails for marketing, sales, and more with just a few clicks.",
      img: "https://js.seapik.com/image/content-generator/ai_1.png",
      url: "/ai-writer/email",
    },
    {
      parent_type: "popular_tools",
      type: "blog",
      title: "Blog ai writer",
      desc: "Create captivating introduction and section paragraphs to make your blog stand out and keep your readers hooked.",
      img: "https://js.seapik.com/image/content-generator/ai_2.png",
      url: "/ai-writer/blog",
    },
    {
      parent_type: "popular_tools",
      type: "web_seo",
      title: "SEO Meta Title & Description",
      desc: "Generate SEO-optimized meta titles & meta description that will increase your website's search engine rankings and attract more traffic.",
      img: "https://js.seapik.com/image/content-generator/ai_3.png",
      url: "/ai-writer/web-seo",
    },
    {
      parent_type: "popular_tools",
      type: "profile_bio",
      title: "Profile Bio",
      desc: "Create vibrant and inspiring bios for your social media accounts to engage more followers and establish your personal brand.",
      img: "https://js.seapik.com/image/content-generator/ai_4.png",
      url: "/ai-writer/profile-bio",
    },
    {
      parent_type: "popular_tools",
      type: "lyric",
      title: "Song Lyrics generator",
      desc: "Generate creative and original lyrics using the AI-powered song generator to bring your music to life.",
      img: "https://js.seapik.com/image/content-generator/ai_5.png",
      url: "/ai-writer/lyric",
    },
    {
      parent_type: "popular_tools",
      type: "ad",
      title: "Ad copy generator",
      desc: "Generate personalized digital advertisements with enterprise-grade marketing copy to promote your products and services effectively.",
      img: "https://js.seapik.com/image/content-generator/ai_6.png",
      url: "/ai-writer/ad",
    },
    {
      parent_type: "popular_tools",
      type: "slogan",
      title: "Slogan generator",
      desc: "Generate a distinctive and engaging slogan for your company or brand to make users easily recall you.",
      img: "https://js.seapik.com/image/content-generator/ai_7.png",
      url: "/ai-writer/slogan",
    },
    {
      parent_type: "popular_tools",
      type: "paragraph",
      title: "Paragraph rewriter",
      desc: "Use this amazing free tool to rewrite any paragraph and make it sound more authentic and engaging, captivating your readers' attention.",
      img: "https://js.seapik.com/image/content-generator/ai_8.png",
      url: "/ai-writer/paragraph",
    },
    {
      parent_type: "popular_tools",
      type: "caption",
      title: "Caption generator",
      desc: "Generate clever and concise social media captions base on your description.",
      img: "https://js.seapik.com/image/content-generator/ai_9.png",
      url: "/ai-writer/caption",
    },
    {
      parent_type: "popular_tools",
      type: "research_paper",
      title: "Research paper writer",
      desc: "AI writing templates can be customized for all types of essays, making it easy to write high-quality academic papers.",
      img: "https://js.seapik.com/image/content-generator/ai_10.png",
      url: "/ai-writer/research-paper",
    },
    {
      parent_type: "popular_tools",
      type: "essay_writer",
      title: "Ai essay writer",
      desc: "Our goal is to help you produce better quality content. Through our assistance, you can rest assured that your work will be up to par.",
      img: "https://js.seapik.com/image/content-generator/ai_11.png",
      url: "/ai-writer/essay-writer",
    },
    {
      parent_type: "popular_tools",
      type: "headline",
      title: "Linkedin headline generator",
      desc: "Leverage AI to generate captivating LinkedIn headlines that will entice users to visit your profile and learn more about you.",
      img: "https://js.seapik.com/image/content-generator/ai_12.png",
      url: "/ai-writer/headline",
    },
    {
      parent_type: "popular_tools",
      type: "instagram_hashtag",
      title: "Instagram hashtag generator ",
      desc: "Leverage our cutting-edge Free AI Instagram Hashtag Generator to generate engaging headlines that will propel your Instagram presence and amplify your impact on the platform.",
      img: "https://js.seapik.com/image/content-generator/ai_13.png",
      url: "/ai-writer/instagram-hashtag",
    },
    {
      parent_type: "popular_tools",
      type: "idea",
      title: "Idea generator",
      desc: "This idea generator is a clever helper that can provide ideas for any topic, giving you the inspiration and creativity you need.",
      img: "https://js.seapik.com/image/content-generator/ai_14.png",
      url: "/ai-writer/idea",
    },
    {
      parent_type: "popular_tools",
      type: "story",
      title: "Story generator",
      desc: "Use AI to generate ideas and write captivating fiction stories effortlessly, enhancing your creativity and productivity.",
      img: "https://js.seapik.com/image/content-generator/ai_15.png",
      url: "/ai-writer/story",
    },
  ],
};

const imgs = {
  popular_tools:
    "https://js.seapik.com/image/content-generator/20231031/icon_3.png",
  others: "https://js.seapik.com/image/content-generator/20231031/icon_17.png",
  writing: "https://js.seapik.com/image/content-generator/20231031/icon_2.png",
  business:
    "https://js.seapik.com/image/content-generator/20231031/icon_19.png",
  education:
    "https://js.seapik.com/image/content-generator/20231031/icon_5.png",
  marketing:
    "https://js.seapik.com/image/content-generator/20231031/icon_9.png",
  entertainment:
    "https://js.seapik.com/image/content-generator/20231031/icon_11.png",
  office: "https://js.seapik.com/image/content-generator/office.png",
  analytical_consulting:
    "https://js.seapik.com/image/content-generator/analytical.png",
  social_media: "https://js.seapik.com/image/content-generator/social.png",
};
